# Generated by Django 3.1.2 on 2020-11-21 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Techniques_Lists', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Techinques',
        ),
    ]
